# Site settings
title: "Kanha's Study Journal"
description: "Notes on what I'm learning — algorithms, systems, ML, and building things."
url: "https://songeamkanha.github.io"
baseurl: "" # Leave this empty unless your site is in a subdirectory

# Build settings
theme: jekyll-theme-minimal # Replace with your theme's name
# The default theme for Jekyll, you can change this to another Jekyll theme

# Markdown settings
markdown: kramdown
highlighter: rouge

# Site navigation
permalink: pretty # Makes URLs clean and readable

# Exclusions
exclude:
  - "README.md" # Files to exclude from the site build
  - "Gemfile"
  - "Gemfile.lock"

# Plugins
plugins:
  - jekyll-feed # Automatically generates an Atom feed for your site
  - jekyll-seo-tag # Adds SEO tags for better search engine optimization
  - jekyll-sitemap

# Author details
author:
  name: Kanha Songeam

#navigation to each main page
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "Contact"
    url: "/contact/"
